{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "bde0145a-2dce-437a-ab2b-d0f4cb1044d8",
   "metadata": {},
   "source": [
    "# agrobased loan default prediction model code"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "8ab412a2-79b7-48f2-a04a-ddffcd40c691",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import numpy as np\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.preprocessing import OneHotEncoder\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8e0cd7e6-66b5-4efc-9bc1-16cd33c891eb",
   "metadata": {},
   "source": [
    "# import the saved model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "67f4ec43-b078-48c0-b3e0-d9ef06f21eac",
   "metadata": {},
   "outputs": [],
   "source": [
    "rf=joblib.load('rf_model.joblib')"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e62ba049-5ce4-4469-b25e-c647b3df1216",
   "metadata": {},
   "source": [
    "# Define the prediction function and Predict loan eligibility"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "6d6df3ec-3361-4d6f-a96d-d2deebb3c9c7",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "def predict(person_age, off_farm_income_ZAR, land_ownership, farming_experience, loan_intent, loan_grade, \n",
    "loan_amnt_ZAR, loan_int_rate, loan_percent_income, cb_person_default_on_file, cb_person_cred_hist_length): \n",
    "\n",
    "    if land_ownership == 'RENT':\n",
    "        land_ownership = 0\n",
    "    elif land_ownership == 'MORTGAGE':\n",
    "        land_ownership = 1\n",
    "    elif land_ownership == 'OWN':\n",
    "        land_ownership = 2\n",
    "    elif land_ownership == 'OTHER':\n",
    "        land_ownership = 3\n",
    "\n",
    "    if loan_intent == 'POULTRY':\n",
    "        loan_intent = 0\n",
    "    elif loan_intent == 'VETERINARY':\n",
    "        loan_intent = 1\n",
    "    elif loan_intent == 'OTHER':\n",
    "        loan_intent = 2\n",
    "    elif loan_intent == 'STOCKFEED':\n",
    "        loan_intent = 3\n",
    "    elif loan_intent == 'DEBTCONSOLIDATION':\n",
    "        loan_intent = 4\n",
    "    elif loan_intent == 'HOTICULTURE':\n",
    "        loan_intent = 5\n",
    "\n",
    "    if loan_grade == 'A':\n",
    "        loan_grade = 0\n",
    "    elif loan_grade == 'B':\n",
    "        loan_grade = 1\n",
    "    elif loan_grade == 'C':\n",
    "        loan_grade = 2\n",
    "    elif loan_grade == 'D':\n",
    "        loan_grade = 3\n",
    "    elif loan_grade == 'E':\n",
    "        loan_grade = 4\n",
    "    elif loan_grade == 'F':\n",
    "        loan_grade = 5\n",
    "    elif loan_grade == 'G':\n",
    "        loan_grade = 6\n",
    "    \n",
    "    if cb_person_default_on_file == 'N':\n",
    "        cb_person_default_on_file = 0\n",
    "    elif cb_person_default_on_file == 'Y':\n",
    "        cb_person_default_on_file = 1\n",
    "\n",
    "    prediction = model.predict(pd.DataFrame([[person_age, person_income, person_home_ownership, person_emp_length, loan_intent, loan_grade, \n",
    "loan_amnt, loan_int_rate, loan_percent_income, cb_person_default_on_file, cb_person_cred_hist_length]], \n",
    "columns=['person_age', 'off_farm_income_ZAR', 'land_ownership', 'farming_experience', 'loan_intent', 'loan_grade', \n",
    "'loan_amnt_ZAR', 'loan_int_rate', 'loan_percent_income', 'cb_person_default_on_file', 'cb_person_cred_hist_length']))\n",
    "    return prediction\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0a8a218b-d486-4a46-b070-cfdbae07b588",
   "metadata": {},
   "source": [
    "# the application\n",
    "# streamlit run C:\\Users\\TIRIVANGANI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\ipykernel_launcher.py "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "4c46dd64-cd5f-4a80-b943-eb66c4c0f532",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-01 15:00:59.842 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.028 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\TIRIVANGANI\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-11-01 15:01:12.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.036 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.041 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.047 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.051 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.055 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.062 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.066 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.154 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.156 Session state does not function when running a script without `streamlit run`\n",
      "2025-11-01 15:01:12.164 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.169 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.173 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.191 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.204 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.250 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.259 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.271 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.291 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.300 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.325 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.346 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.355 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.365 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.439 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.500 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.526 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.536 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.547 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.554 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.564 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.599 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.617 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.649 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.668 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.692 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.703 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.713 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.721 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.731 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.798 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.806 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.896 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.914 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.922 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.933 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.940 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.967 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.975 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.986 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:12.996 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.005 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.014 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.022 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.032 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.040 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.050 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.067 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.128 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.153 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.163 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.171 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.182 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.190 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.200 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-01 15:01:13.208 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "st.title('LOAN DEFAULT PREDICTOR_ZW')\n",
    "# st.image(\"\"\"https://www.thestreet.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MTY4NjUwNDYyNTYzNDExNTkx/why-dominion-diamonds-second-trip-to-the-block-may-be-different.png\"\"\")\n",
    "st.header('Enter the characteristics of applicant:')\n",
    "person_age = st.number_input('Age of Applicant:', min_value=0.0, max_value=120.0, value=1.0)\n",
    "off_farm_income_ZAR = st.number_input('Income of Applicant:', min_value=0.0, max_value=1000000.0, value=1.0)\n",
    "land_ownership = st.selectbox('Land status:', ['RENT', 'MORTGAGE', 'OWN', 'OTHER'])\n",
    "farming_experience = st.number_input('Years of farming:', min_value=0.0, max_value=30.0, value=1.0)\n",
    "loan_intent = st.selectbox('LOAN INTENT:', ['POULTRY', 'VETERINARY', 'OTHER', 'STOCKFEED', 'DEBTCONSOLIDATION', 'HOTICULTURE'])\n",
    "loan_grade = st.selectbox('LOAN GRADE:', ['A', 'B', 'C', 'D', 'E', 'F', 'G'])\n",
    "loan_amnt_ZAR = st.number_input('Loan Amount:', min_value=0.0, max_value=1000000.0, value=1.0)\n",
    "loan_int_rate = st.number_input('Interest Rate:', min_value=0.0, max_value=100.0, value=0.01)\n",
    "loan_percent_income = st.number_input('Percentage of loan to Income', min_value=0.0, max_value=1.0, value=1.0)\n",
    "cb_person_default_on_file = st.selectbox('Previous History of Default:', ['N','Y'])\n",
    "cb_person_cred_hist_length = st.number_input('Length of Credit History (In Years)', min_value=0.0, max_value=50.0, value=1.0)\n",
    "\n",
    "\n",
    "if st.button('Predict Default'):\n",
    "    loan_status = predict(person_age, off_farm_incomeZAR, land_ownership, farming_experience, loan_intent, loan_grade, \n",
    "loan_amnt_ZAR, loan_int_rate, loan_percent_income, cb_person_default_on_file, cb_person_cred_hist_length)\n",
    "    result = 'YES' if loan_status[0] == 1 else 'NO'\n",
    "    st.success(f'Application Result: {result}')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count"
   "id": "ca8841d4-5481-4e82-88c0-268c62788fb3",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
